[versions]
kotlin           = "2.4.20"
mockk            = "1.14.11"
spring-boot      = "4.1.1"
spring-dep-mgmt  = "1.1.7"

[plugins]
kotlin-jvm       = { id = "org.jetbrains.kotlin.jvm",            version.ref = "kotlin"           }
kotlin-spring    = { id = "org.jetbrains.kotlin.plugin.spring",  version.ref = "kotlin"           }
spring-boot      = { id = "org.springframework.boot",            version.ref = "spring-boot"      }
spring-dep-mgmt  = { id = "io.spring.dependency-management",     version.ref = "spring-dep-mgmt"  }

[libraries]
junit-platform-launcher      = { group = "org.junit.platform",       name = "junit-platform-launcher"      }
kotlin-reflect               = { group = "org.jetbrains.kotlin",     name = "kotlin-reflect"               }
kotlin-test-junit5           = { group = "org.jetbrains.kotlin",     name = "kotlin-test-junit5"           }
mockk                        = { group = "io.mockk",                 name = "mockk",                       version.ref = "mockk"   }